#spring.profiles.active=dev

spring.application.name=play

server.port=8080
server.servlet.context-path=/platzi/prod/api

langchain4j.open-ai.chat-model.api-key=demo
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d748lfuuk2gs73a0tk2g-a.oregon-postgres.render.com/platzi_play_db_izaw
spring.datasource.username=mysql
spring.datasource.password=wNcaP4hGKXkh3BUxU1vBueuR843Vzmat

spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=update





